### ISSUE TITLE
"Game is not running" after switching accounts

### ISSUE THREAD

**Issue by mahamoti64** [Razviar/mtgap#191] opened 2020-09-30 05:19 UTC
https://mtgarena.pro/collection/?Mahamoti64#rulings-1;srt-11;direct-0;smrtsrhc-passage
I don't have any copies of Fabled Passage from M21, but the collection manager shows that I have two copies.

There are some other cards that it shows that I have, but I don't actually have them.

I'm running Windows 10.  App version 2.1.9.

So here is the actual issue. My daughter also plays Arena on my computer. Her Arena username is silv3rhawk.  She does *not* have an account on MTGA Pro.  She has two M21 fabled passage cards.  The MTGA Pro tracker is counting her cards as being in my collection.

I can send logs if that helps.

- Is this a known issue?  Does MTGA Pro support multiple users on the same computer?
- Would it work better if both of us had an account on MTGA Pro?  (instead of just me)
- I'd like to re-sync my collection to be correct in my MTGA Pro account, if possible - is that possible? - but then I assume the next time my daughter logs in to Arena, my MTGA Pro account collection will be wrong again.

For "steps to reproduce" , I expect you need to run Arena, then log out, then log in with a different account on the same computer.  That's generally what we do.  :)  Again, as per my question above, it's possible that the bug is specific to a scenario where one player has an MTGA Pro account, and the other does not.

**Comment by Razviar** [comment] 2020-09-30 05:42
Unfortunately multiple accounts support is buggy in our tracker. We are trying to fix it, but no luck for now. I can't promise any ETA on this issue.

**Comment by Razviar** [comment] 2020-09-30 06:57
I just pushed 2.1.10 version of tracker, where we tried to fix this. Please check it out

**Comment by Razviar** [comment] 2020-10-19 11:09
Version 2.1.11 finally resolves this issue.

**Comment by mahamoti64** [comment] 2020-10-20 14:15
Thanks for the patch.  My daughter hardly ever runs Arena so I haven't
really been able to thoroughly test the patch.  It looks like the progress
on the web page is correctly showing how many rares I have, but again, I
haven't double checked if there are any rares that my daughter has that I
don't.

I do have another issue, which is related, so I don't know if it would be
considered the same issue, or if I should file a separate issue.

The issue is that once my daughter logs in to Arena, I have to restart the
tracker for it to work again.  i.e. if she logs out, and I log in, it still
never recognizes that the game is running, or reads the new log files.  For
example, right now, the game is running, but the tracker says   "Game is
not running!"  And for MTGA nick it shows my daughter's account.

This has a relatively easy workaround - exit the tracker and restart it -
but I thought I should mention it anyway in case you can fix it. (Should I
file a new issue on GitHub?)

Thanks,
Jeff

**Comment by Razviar** [comment] 2020-10-20 15:18
@mahamoti64 Hi, Jeff!
Thanks for letting me know about this issue. But I wasn't able to reproduce it. I logged in with one account, then logged out, logged in with second account and Tracker got another user at once. Can you please describe your scenario, when exactly are you getting that "game not running" message?

**Comment by mahamoti64** [comment] 2020-10-20 19:45
Again, our scenario is that I have an account on mtga pro tracker, and my
daughter does not.
Test case:
1. Everything is "working" ; tracker is running, Arena is running, I'm
logged in.
2. I log out; tracker says "Awaiting user credentials to appear in log..."
3. My daughter logs in.  tracker says, "Error: Parsing paused: new user
account must be synced or skipped"
4. My daughter quits Arena.  Tracker says, "Game is not running!"
5. I launch Arena; log out my daughter, and log in; tracker says "Game not
running" , still shows daughter's Nickname.

I can send screenshots if that helps.

At this point, the only way the tracker will work is if I exit it and
re-launch it.  It is "stuck" with my daughter's MTGA nick: displayed until
I quit.

Okay, I just clicked "Skip Account" and now it seems to have picked up my
account again.  It looks like that fixes it.  So, never mind.  I probably
should have done that months ago.  :)

It looks like you can close this issue again.  I'll let you know if I run
into the inventory issue again.

Thanks,
Jeff

**Comment by Razviar** [comment] 2020-10-24 11:00
Yep, when new account is detected, it needs to be synced or skipped. This is workflow as intended, so I'm closing the issue.

**Closed by Razviar** 2020-10-24 11:00 UTC
Labels: bug
