### ISSUE TITLE
Draft pick evaluation broke in 2.0.27 (works in 2.0.25)

### ISSUE THREAD

**Issue by graczyk** [Razviar/mtgap#64] opened 2019-12-28 01:08 UTC
**Describe the bug**
Draft pick evaluation used to work in 2.0.25. Once updated to 2.0.27, it broke.

**To Reproduce**
1. Install 2.0.25 and configure tracker
2. Begin a ranked draft, note that the tracker will render draft picks and ratings
3. Wait for auto update to 2.0.27
4. Tracker will not detect that we're in a draft and will not show anything, even when 'Me' is selected

**Expected behavior**
Draft pick evaluation works as it did in 2.0.25

**Screenshots**
![image](https://user-images.githubusercontent.com/1758079/71537052-6ff4ae80-28cb-11ea-9489-857142025646.png)
Note that the tracker is visible, but nothing is being rendered

**Desktop (please complete the following information):**
- Windows 10

**Additional context**
Let me know if I can provide any logs or help debug the issue

**Comment by graczyk** [comment] 2019-12-28 01:22
Upon further inspection, it looks like the Tracker is totally broken. It's not working for me in constructed matches either. It shows the name of my deck, but no cards. Same for my opponent.

**Comment by Razviar** [comment] 2019-12-28 06:21
Looks like it's not global issue. We just checked and it's all working. Also, no complains from other users. Can you check tracker installation folder for logs? You should find some .log files in appdata/roaming/mtgaprotracker folder

**Comment by friscoMad** [comment] 2019-12-29 13:02
I have the same issue and I have no logs in that folder:
![2019-12-29 14_02_00-MTGAproTracker](https://user-images.githubusercontent.com/487098/71557248-d8669b80-2a43-11ea-897f-837225d70dfb.png)

**Comment by Razviar** [comment] 2019-12-29 13:12
Have you tried standard recovery steps? Wipe settings, reset everything including PC, sync again?

**Comment by graczyk** [comment] 2019-12-31 21:52
Yep. I also have no logs in that folder. 2.0.28 didn't help either, same symptoms.

Once I have the time to figure out how to build/debug the app, I can try taking a look at what's wrong.

**Comment by Razviar** [comment] 2019-12-31 21:54
28th wasn't meant to solve this, so no surprise it doesn't. If you will have any questions about building, feel free to ask

**Comment by friscoMad** [comment] 2020-01-03 21:30
> Have you tried standard recovery steps? Wipe settings, reset everything including PC, sync again?

I will start a new draft tomorrow, I have done as requested, wipe settings, reset pc (so no apps runing), sync again, still I see no logs in the folder you said, so can you please tell me how to enable that logs?

Btw: I did see that the version updater is storing some info in: AppData\Local\mtgaprotracker instead of AppData\Roaming\MTGAproTracker

**Comment by friscoMad** [comment] 2020-01-05 19:31
Ok, I did clone and started with dev tools to see what was happening after the new draft also had the issue.
From what I see the problem does not reproduce after restarting the mtga client with the draft on course so I think the issue is that the 'set-userdata' message is not received between the draft end and the match start, sadly this can only be tested once per draft so I can not find anything else until the next draft I play.

**Comment by Razviar** [comment] 2020-01-05 19:34
In 29th version there's telemetry enabled, so all logs are being uploaded automatically. We are investigating that set-userdata issue. And yes, it's very hard to debug, since drafts are not cheap to to with them like that :)

**Comment by friscoMad** [comment] 2020-01-11 14:18
Ok, some more info, the deck should be set with the 'deck-submission' event after contruction or sideboarding, for some reason on my overlay process, 'overlayConfig.metaData' is falsy so it returns instead of processing the 'deck-submission' event it just returns.
Why metaData is null? I have no clue, everything seems ok and after restarting the tracker several times I see no issues with it, the set-metadata is sent with info everytime I restart, maybe it just happens in the first start after a version update?.

**Comment by friscoMad** [comment] 2020-01-11 18:01
Plot twist I started a new draft without restarting the tracker (so the meta was debugged and it was present) but I did not debug that deck submission but it is still not showing the correct dect.
As I had some traces activated what I found is that my 'playerDecks' vars have 2 draft decks: 
'ELD_Quick_Draft' (the old one) and 'QuickDraft_ELD_20191011' (the one I drafted in the current draft even if the date in the name makes no sense) and the match started event does send the eventID 'ELD_Quick_Draft'

Sadly I had no traces inside the deck-submission event, but here is a screenshot of what I can see (this is v.30 code just with console.logs patches).
![2020-01-11 18_59_26-Developer Tools - http___localhost_3000_overlay_window](https://user-images.githubusercontent.com/487098/72208599-bb4eb580-34a4-11ea-94a5-b98bd2f26d61.png)

**Comment by Razviar** [comment] 2020-01-11 18:10
Thanks for hunting that down, it will help a lot

**Comment by Razviar** [comment] 2020-01-12 13:51
Thanks to your debugging it's fixed in v.2.0.31

**Closed by Razviar** 2020-01-12 13:51 UTC
Labels: can't reproduce
