### ISSUE TITLE
tracker not recognizing game, game exe is running and so it is the tracker

### ISSUE THREAD

**Issue by iurirolho** [Razviar/mtgap#196] opened 2020-10-17 00:20 UTC
somehow I reinstalled the game and the tracker after a long break and now the tracker does not work, I boot the tracker first then game then it says the game is not running even  is running anything I can do
![image](https://user-images.githubusercontent.com/20928051/96323871-d42d5e00-1016-11eb-91da-46e971480798.png)

**Comment by Razviar** [comment] 2020-10-17 03:52
Have you tried to restart everything: the tracker, mtga itself, pc

**Comment by iurirolho** [comment] 2020-10-17 13:17
my pc just finished a reboot after a update today so am going to try again soon and then update

**Comment by iurirolho** [comment] 2020-10-17 13:40
weird now the app works for some reason

**Comment by iurirolho** [comment] 2020-10-17 13:47
now its not working again for some reason

**Comment by iurirolho** [comment] 2020-10-17 13:48
played a match then it went to that error again

**Comment by Razviar** [comment] 2020-10-19 11:07
We were unable to reproduce this issue. If data is uploading normally and you can see your progress on site, then it's okay. I'm closing this for now, but will reopen if needed.

**Closed by Razviar** 2020-10-19 11:07 UTC
