### ISSUE TITLE
Tracker not finding user ID in logs after 8/24 update

### ISSUE THREAD

**Issue by dknedlik** [Razviar/mtgap#263] opened 2021-08-25 01:45 UTC
![image](https://user-images.githubusercontent.com/6331754/130712595-106668df-e8e1-4d3e-98c2-e8a645e8f7c4.png)

Windows 10, detailed logs enabled.  Tracker hangs at "Awaiting User ID to appear in log".

To reproduce: Start game client and tracker.

**Comment by FriendOfEntropy** [comment] 2021-08-25 03:40
Experiencing the same.  Also confirmed that my log file does still have at least one line with user ID

`[Accounts - Login] Logged in successfully. Display Name: FriendOfEntropy####`

**Comment by Razviar** [comment] 2021-08-25 04:37
Unfortunately it's not user ID, it's only screen name. ID is the random set of characters. We will investigate the changes.

**Comment by Razviar** [comment] 2021-08-25 06:45
WOTC messed up logs again, pushing us even harder to take hardcore approach and start modding the game in order to get needed data from it. We are currently looking into possible modding opportunities, but these developments will take a lot of time, unfortunately.

**Comment by ZakVanstrom** [comment] 2021-08-25 07:14
Are you implying this will be a long-term issue due to the new back-end update? Is there a community of modders working on this? As a back-end dev & lover of MTG I'd be glad to spend time helping with development

**Comment by Razviar** [comment] 2021-08-25 07:21
@ZakVanstrom the main issue here is WOTC cutting down logs. They removed crucial information from log, like data about player collection etc. But in the game itself all this data is present. And if we could mod the game to make it log what we need, we could find long-term solution for this issue. Currently there's only one person working on mod (it's me).

**Comment by ZakVanstrom** [comment] 2021-08-25 07:51
Oh okay--When you say that the game itself has all the data, that means a mod would have to modify their client code to report that data externally, so it can be scraped. 

As of now, the app currently scrapes only from the frequently-updated local logs, right? Doing this doesn't seem impossible, but seems pretty inconvenient. Does this mean that MTGA's devs are discouraging these type add-ons, or is it just poor QA of their log-outputs?

**Comment by Razviar** [comment] 2021-08-25 08:00
@ZakVanstrom WOTC official position is that tracking is allowed as long as it's not cheating (like, not getting the data which is not accessible for user through common interface).

MTGA is pretty much standard Unity game, with all consequences. We already attempted to use Harmony for modding, but no luck for now. If you are really into it, and want to dive in, please contact me via admin@mtgarena.pro

**Comment by kevin-smets** [comment] 2021-08-25 11:20
Umph, this is going to break quite a bit of 3rd party tools I imagine. Thanks for the clarification and hopefully you can get it to work.

**Comment by Li2012** [comment] 2021-09-03 15:06
Hi Razviar, 
Thanks very much for taking the time to answer peoples questions. Very helpful for me to understand the issue. 

One follow up question: it seems untapped.gg is able to track all the in game state fine. For their twitch pluggin, as a viewer I can hover streamer's board, hands, graveyard and see realtime info (very accurate). How could they achieve this if the logs other tracker depends are missing important info?

**Comment by Razviar** [comment] 2021-09-03 15:26
@Li2012 they are using memory reading technique, connecting directly to Mono (it's unity part). It's very complicated, we are making something similar, but it's really hard task. If we assume score, tracking memory vs tracking text logs is like 50 to 1

**Comment by Li2012** [comment] 2021-09-03 23:51
> 
> 
> @Li2012 they are using memory reading technique, connecting directly to Mono (it's unity part). It's very complicated, we are making something similar, but it's really hard task. If we assume score, tracking memory vs tracking text logs is like 50 to 1

Thanks for the info. I never known Mono before. After I search a bit, it sounds like Mono is comparable to 'JVM' or '.Net' for unity. 

I guess the difficulty (the 50 score you gave) comes from having to reverse engineer black-box system? What's not helpful is untapped.gg is not open source, so others wouldn't be able to reuse their work.

**Comment by Razviar** [comment] 2021-09-19 11:37
Closing in favor of #266

**Closed by Razviar** 2021-09-19 11:37 UTC
Labels: bug
