### ISSUE TITLE
As others have stated, logs are not parsing

### ISSUE THREAD

**Issue by cryptotoad** [Razviar/mtgap#351] opened 2023-04-07 09:06 UTC
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- CryptoToad#07025
- 
**Your Desktop:**
 - OS: Windows 10
 - App type: Standalone
 - App Version [2.2.25](https://github.com/Razviar/mtgap/releases/tag/v2.2.25)

**Describe the bug**
Game logs all get skipped

**To Reproduce**
Happens every time

**Comment by Razviar** [comment] 2023-04-07 09:30
Have you tried to wipe settings?

**Comment by gigru** [comment] 2023-04-10 01:40
the same problem

**Comment by Razviar** [comment] 2023-04-10 08:30
Duplicate of #348

**Closed by Razviar** 2023-04-10 08:30 UTC
Labels: bug
