### ISSUE TITLE
Can't see rewards/progress after 8/24 update

### ISSUE THREAD

**Issue by CrazzyJagger** [Razviar/mtgap#267] opened 2021-09-09 07:02 UTC
mtga.cc/u/CrazzyJagger
https://mtgarena.pro/rewards/
https://mtgarena.pro/boosters/
https://mtgarena.pro/progress/

 - OS: Windows 7 x64
 - App type: Standalone
 - App Version 2.1.35

![bug_rewards](https://user-images.githubusercontent.com/90376544/132638386-e0fe46a3-b0a0-4b69-ab69-fddc5e5c97c7.jpg)
![bug_boosters](https://user-images.githubusercontent.com/90376544/132638396-fe532a32-6c7b-47e2-b42f-194907927cf1.jpg)

Matches has statistic - log is parsed
![no_bug_matches](https://user-images.githubusercontent.com/90376544/132638393-b2bb72bd-edff-48fb-9d69-ea75e436be77.jpg)

**Comment by Razviar** [comment] 2021-09-09 08:58
Closing as duplicate of #226 , it's the same issue

**Closed by Razviar** 2021-09-09 08:58 UTC
Labels: bug
