### ISSUE TITLE
The tracker eating memory

### ISSUE THREAD

**Issue by count1068** [Razviar/mtgap#21] opened 2019-11-27 17:09 UTC
![mtgaprotracker](https://user-images.githubusercontent.com/58267768/69743209-058c0980-1179-11ea-8db0-2b762a2338dc.jpg)

I didn't close the tracker after I exited the MTGA, but just kept it minimized. Nothing really happened for a few hours, but suddenly the computer was lagging, and the task manager showed that mtgaprotracker.exe used up 7GB and 2GB memories. After killing the 2 process, the computer returned to normal. I tried again, and similar things happened after another few hours. 
I also noticed that there was only 1 mtgaprotracker.exe process which used about 30MB when I just exited the MTGA, and it remained so when I check the task manager now and then. But both time the computer was lagging, there were 2 mtgaprotracker.exe process.

**Comment by Razviar** [comment] 2019-11-27 17:10
We are investigating this issue

**Comment by privera-git** [comment] 2019-11-28 18:40
Same thing for me. It's really frustrating.

**Comment by Razviar** [comment] 2019-11-28 18:47
Are you having windows 7 as well?

**Comment by patmey** [comment] 2019-11-28 23:38
I'm using windows 7 to play Arena and I also suffer from this but when it happens to me the tracker also takes up 30-40% of my cpu cycles on all 4 cores(3ghz core2 quad).

The tracker is usually stuck on 'checking for updates' when it happens.

**Comment by privera-git** [comment] 2019-11-28 23:51
In my case is Windows 10 Home v1903.

**Comment by count1068** [comment] 2019-11-29 07:58
I'm using Windows 7 SP1  6.1.7601

**Comment by goldmojo** [comment] 2019-11-29 22:42
Same here : Windows 7 x64

**Comment by Razviar** [comment] 2019-11-30 05:22
Question: is this happening constantly, all the time you use tracker, or just happened once?

**Comment by patmey** [comment] 2019-11-30 08:27
It happens often enough I started to let the Windows task manager run in the background so i can kill the tracker quickly in case it starts to lock up my system again.

**Comment by goldmojo** [comment] 2019-11-30 10:35
It happens after few hours (2-3 hours) of non use of the tracker.
- At windows startup : mtgatracker.exe is started automatically as 4 processes.
- Only 2 of them are still running when memory usage is high (2 GB / 3 GB of memory each).
It seems that mtgatracker.exe memory usage is not stable, memory consumption change even when non using the tracker. May be a memory leak ?

**Comment by jeohist** [comment] 2019-11-30 12:31
I think it might be related to #10, I experienced the same symptoms

**Comment by count1068** [comment] 2019-11-30 16:57
It happened another 2 times for me, make it totally 4 times. Then I decided not to use it until next version released.

**Comment by pugalo** [comment] 2019-11-30 17:53
> 
> Question: is this happening constantly, all the time you use tracker, or just happened once?

Windows 10 1903, happens all the time. Not running the app till this gets fixed.

**Comment by Razviar** [comment] 2019-11-30 18:06
Question: what country are you from anyone who's facing this?

**Comment by pugalo** [comment] 2019-11-30 18:11
Russia, but why would it matter?

**Comment by Razviar** [comment] 2019-11-30 18:16
Because in Russia some IP addresses are blocked by lovely roskomnadzor, and this might break updating mechanism. But we need to confirm if it's the case.

**Comment by goldmojo** [comment] 2019-11-30 18:24
Good news @Razviar : The problem seems to be corrected in 2.0.15 when automatic update is disabled (I didn't try with the update feature switched on).

**Comment by privera-git** [comment] 2019-12-01 03:19
I'm from Chile, if that's useful. As far as I know there are no restrictions in Chile to internet browsing.

I used to start the tracker with Windows. PC turned slow every time even when I didn't run the game. If I wasn't there to kill the tracker I can't even use the task manager. Now, I'm just open the tracker, wait for sync and close it immediately.

I'll try switching update feature off.

**Comment by Razviar** [comment] 2019-12-01 07:04
Okay, then Russian theory is not confirmed, for now we'll recommend as temporary solution to enable manual updates on settings. And will investigate what's happening with auto updates

**Comment by count1068** [comment] 2019-12-01 13:52
I'm from Taiwan. I don't think we have particular internet restrictions in Taiwan.

**Comment by Razviar** [comment] 2020-02-08 10:46
Since new versions are not showing this unwanted behavior, I'm closing this.

**Closed by Razviar** 2020-02-08 10:46 UTC
Labels: can't reproduce
