### ISSUE TITLE
progress mixed from multiple accounts on the same machine

### ISSUE THREAD

**Issue by Kellerhefe** [Razviar/mtgap#113] opened 2020-05-02 05:50 UTC
I have two accounts on MTGA and two on MTGAPRO.
For a while now if i play with the other account the progress is shared on the main account. Daily wins, card rewards, decks played etc.

**Comment by Razviar** [comment] 2020-05-02 06:06
You mean events from one account are rendered for another? Can you post some links with comments. Like, your matches page with comment which matches are wrongfully linked to this account

**Comment by Kellerhefe** [comment] 2020-05-02 06:10
![image](https://user-images.githubusercontent.com/55648440/80856692-45857a00-8c4c-11ea-883a-44f5c8c91666.png)
the green outlined are frome the other account.

**Comment by Kellerhefe** [comment] 2020-05-02 06:18
![image](https://user-images.githubusercontent.com/55648440/80856807-7e721e80-8c4d-11ea-8351-ca14dbd84179.png)

**Comment by Razviar** [comment] 2020-05-02 06:30
Thank you, we will look into this

**Comment by Kellerhefe** [comment] 2020-05-02 06:32
No, thank you for looking into this for me.

**Comment by gyordanoreis** [comment] 2020-05-04 03:14
Just a BUMP to say I had the same problem.

Even after trying to Skip the account logs, it stays in a bugged state:

![image](https://user-images.githubusercontent.com/34443267/80933907-12ea9700-8d9c-11ea-9837-e468be0d0e92.png)

Also I can't unlink, pops this error:

![image](https://user-images.githubusercontent.com/34443267/80933945-2eee3880-8d9c-11ea-8550-d02452e97d19.png)

**Comment by Razviar** [comment] 2020-05-04 03:38
Yeah, I can confirm it's global bug, affecting all users with multiple accounts. For some reason multiple accounts is our constant pain, we were struggling with them since the very beginning of the tracker operation

**Comment by Razviar** [comment] 2020-05-04 03:54
@gyordanoreis As temporary solution you can go to settings tab and wipe settings. Then sync only one account

**Comment by Razviar** [comment] 2020-05-04 05:55
We deployed v.2.0.44 containing fix for this issue. From now on it should separate data from the accounts. But unfortunately all messed up accounts with mixed data are beyond fixing.

**Comment by Kellerhefe** [comment] 2020-05-04 06:08
Thank you. How can i clear my account and start fresh on mtgapro ?

**Comment by Razviar** [comment] 2020-05-04 09:57
You can remove your account using new account deletion tool here: https://mtgarena.pro/u  (in profile settings, Account Deletion section). Then you can re-create it and sync again.

**Closed** 2020-05-25 09:00 UTC
Labels: bug
