### ISSUE TITLE
Rewards page not updating

### ISSUE THREAD

**Issue by AmazingAvenger** [Razviar/mtgap#268] opened 2021-09-19 11:15 UTC
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: https://mtgarena.pro/u/
- - Link to page/pages are in question: https://mtgarena.pro/rewards/
- Screenshots of issue if applicable 
![afbeelding](https://user-images.githubusercontent.com/91011657/133925395-c8a4cb8f-a895-42af-abc6-9f0c38914ab6.png)

**Your Desktop:**
 - OS: Windows 10
 - App type: Standalone
 - App Version: 2.1.35

**Describe the bug**
The rewards page does not show new content since 24 aug 2021.
I Reinstalled the app
I cleared the cache.
I logged out and in in the app and in the website

**To Reproduce**
1. Go to "Rewards" under "My Arena"

**Comment by Razviar** [comment] 2021-09-19 11:36
Closing as duplicate of #266

**Closed by Razviar** 2021-09-19 11:36 UTC
Labels: bug
