### ISSUE TITLE
Collection progress across all expansions is stuck on Historic

### ISSUE THREAD

**Issue by bqback** [Razviar/mtgap#88] opened 2020-03-03 21:22 UTC
My Historic and Standard collection graphs are identical (both are 0.8%/1.8%), despite me only having standard cards and my lowest Standard completion sitting at 22%/51%.
![image](https://user-images.githubusercontent.com/28458777/75820697-e28f7800-5dad-11ea-8222-f15d4d85c766.png)
![image](https://user-images.githubusercontent.com/28458777/75820754-f804a200-5dad-11ea-9816-586b22423511.png)

The graph does rerender, so I assume it's grabbing data from the wrong place or something?

Furthermore, even a manual calculation showed an issue, as my completion, even accounting for historic sets, should be at 
21.5% total
1/996 DOM, 1/764 RIX, 1/1036 XLN, 2/1000 M19, 234/996 RNA, 252/996 GRN, 238/996 WAR, 271/996 M20, 350/996 ELD, 754/996 THB => 2104/9772
38.4% unique 
1/249 DOM, 1/191 RIX, 1/259 XLN, 2/250 M19, 128/249 RNA, 136/249 GRN, 134/249 WAR, 135/249 M20, 169/249 ELD, 232/249 THB => 939/2443
You can find my profile to compare the data [here](mtgarena.pro/u/Liandry).

1.8% unique completion, for example, would require another **49723** unique (939/0.018 - 2443 cards already accounted for) cards to exist in the game, about 3 times the amount of unique cards in _all_ of MtG up to date.

**Comment by Razviar** [comment] 2020-03-04 06:15
So to be clear, cards in mtgapro profile are synced correctly, the issue is only progress chart?

**Comment by Razviar** [comment] 2020-03-12 14:31
Currently this is fixed with new progress calculation technique.

**Closed by Razviar** 2020-03-12 14:31 UTC
