### ISSUE TITLE
Cards that don't get a statistic in constructed?

### ISSUE THREAD

**Issue by Superkurtje** [Razviar/mtgap#289] opened 2021-12-27 10:38 UTC
I am asking how many gamesI have to play with a card before it gets a statistic in DB% and CW%.
For instance I played numerous games with Odric Outrider and Angelic Quartermaster and they still stay at 0%
Is this a bug in your recording?

**Comment by Razviar** [comment] 2021-12-27 10:40
Most likely it's a bug affecting new Alchemy cards. We will investigate it.

**Comment by Superkurtje** [comment] 2021-12-27 10:46
They are not alchemy cards. Just regular midnight hunt and crimson vow cards.

**Comment by Razviar** [comment] 2021-12-27 10:51
Card stats are updated on daily basis, approximately at 2-4AM. Then the cache have to update, it might take additional 6 hours. So you should see updated card stats after roughly a day after card gets spotted in the match. I checked, and stats calculation is working as intended, including Y22 set. So I'm closing the issue. Feel free to add any comments if there will be no stats updates in 36 hours.

**Closed by Razviar** 2021-12-27 10:51 UTC

**Comment by Superkurtje** [comment] 2021-12-27 13:41
Razviar,
I see that in the MTG Arena Pro application they get a rating but not on the website
